
# Basics of numpy 

```
import numpy as np
```
## What is an “array”?
In computer programming, an array is a structure for storing and retrieving data. We often talk about an array as if it were a grid in space, with each cell storing one element of the data. For instance, if each element of the data were a number, we might visualize a “one-dimensional” array like a list:

 



![alt text](<Screenshot 2025-07-11 155316.png>)

In [3]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]



Most NumPy arrays have some restrictions. For instance:

- All elements of the array must be of the same type of data.

- Once created, the total size of the array can’t change.

- The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.


# Matrix multiplication using numpy

In [5]:
import numpy as np

# Define two matrices
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

product_1 = np.dot(matrix_a, matrix_b)
print("Result using np.dot():\n", product_1)

# Method 2: Using the @ operator
product_2 = matrix_a @ matrix_b
print("\nResult using the @ operator:\n", product_2)

# Method 3: Using np.matmul()
product_3 = np.matmul(matrix_a, matrix_b)
print("\nResult using np.matmul():\n", product_3)



Result using np.dot():
 [[19 22]
 [43 50]]

Result using the @ operator:
 [[19 22]
 [43 50]]

Result using np.matmul():
 [[19 22]
 [43 50]]


# Matric multiplication manual checker

In [6]:
l1 = [[1,2],[3,4]]
a = len(l1)
b = len(l1[0])
print(a,b)
print(a==b)

2 2
True


# Function to check if the matrix is jagged

“jagged”; e.g., each row of a two-dimensional array must have the different number of columns.


In [7]:
def checkNotJagged(matrix):
    cloumnLength = 0
    for i in range(len(matrix)):
        if i == 0:
            cloumnLength = len(matrix[0])
            continue
        if len(matrix[i]) != cloumnLength:
            return 1 
    return 0 

l1 = [[1,2],[1,2]]
a = checkNotJagged(l1)
l2= [[1,2],[2]]
b = checkNotJagged(l2)
print (a,b)

0 1


# Code to multiply two matrices 

# Very basic code 

It does not have 
- any checks for if the matrix is jagged
- it uses predefined inputs
- the output matrix is predefined

In [ ]:
matrix_1 = [[1,2],[3,4]]
matrix_2 = [[5,6],[7,8]]

result = [[0,0],[0,0]]

for i in range(2):
    for j in range (2):
        result[i][j] =  